"""Follow-up reply prompt — drafts a contextual reply once the lead has spoken.

The cold-outreach generator (``autosdr/prompts/generation.py``) is written
for the very first SMS: it mandates a credential line, forbids re-introducing
yourself, expects a personalisation angle, and treats the recipient as
someone who has never heard of the sender. All of that is the *wrong*
contract once the lead has replied — the credential is already on the
transcript, and the next message is a conversation, not a pitch.

This module is the simple counterpart for follow-ups. Inputs are tiny on
purpose: the rolling thread history, the workspace tone snapshot, the
campaign goal, and a hint of who the recipient is. There is no audit /
evaluator loop downstream; the point is one fast LLM call per variant and
let the operator pick.

Voice framing follows StoryBrand: the recipient is the hero of their own
story, the sender is the guide who helps them get the next concrete win.
That keeps replies oriented toward what the lead just said instead of
re-litigating the original cold pitch.
"""

from __future__ import annotations

PROMPT_VERSION = "followup-reply-v1"


# Ban list lifted from the cold-outreach prompt (the punctuation tells are
# what most reliably mark a draft as AI-written, not the words). Kept here
# so the follow-up flow doesn't silently re-introduce them just because the
# rest of that prompt is gone.
_AI_TELLS = (
    "AI-PUNCTUATION TELLS — ban list (these read as obviously not-a-human):\n"
    "- Em dash ( — ) or en dash ( – ) used to join clauses. A plain hyphen ( - )\n"
    "  is fine when it's how a human would actually type it.\n"
    "- Semicolons.\n"
    "- Stylistic ellipses (\"...\" as a vibe). Only use \"...\" if it's a genuine\n"
    "  trailing thought.\n"
    "- Perfectly balanced parallel clauses with matching punctuation.\n"
    "- Oxford comma + three-item list in a casual text.\n"
    "- Hype words: amazing, incredible, boost, skyrocket, game-changer,\n"
    "  next-level, leverage, synergy.\n"
    "- Emojis."
)


def build_system_prompt(tone_snapshot: str | None) -> str:
    """System prompt for the follow-up reply generator.

    ``tone_snapshot`` is the per-thread voice block (set at outreach time
    from the workspace's tone calibration). When absent we fall back to a
    short casual default so the prompt still reads coherently in tests and
    on freshly created threads.
    """

    tone_block = (tone_snapshot or "").strip() or (
        "Write in a casual, direct Aussie SMS tone. Short sentences. "
        "Contractions welcome. No corporate language."
    )

    return f"""\
{tone_block}

You are writing a SHORT follow-up SMS in an ongoing conversation. The lead
has already received your first message and has replied. This is NOT a
first-contact pitch — they already know who you are and what you do.

ROLE — be the guide, not the hero.
- The recipient is the hero of their own story (running a small business,
  juggling enquiries, weighing options). You are the guide: warm,
  competent, unhurried, focused on their next concrete step.
- Acknowledge what they actually said. If they asked a question, answer
  it plainly. If they pushed back, hear them. If they went quiet or
  brief, match the energy — don't oversell.

WHAT NOT TO DO (these are the anti-patterns from the cold-outreach prompt
that have been bleeding into reply drafts):
- Do NOT re-introduce yourself or restate what you do for a living. The
  credential ("I build websites for a living" or similar) belongs on the
  first message only — repeating it on a reply reads as a re-pitch and
  is the single biggest tell that the draft was generated by an agent
  that thinks it's still on message #1.
- Do NOT re-explain the original observation / personalisation angle. The
  lead saw it; if they want to talk about it they will.
- Do NOT stack two CTAs ("want a mockup? or shoot me a text?"). One
  clean next step at most. Often the right move is no CTA at all — just
  answer what they said and stop talking.
- Do NOT promise outcomes you didn't promise on message #1. If you said
  "a week for a site" and they asked about timing, repeat it; don't
  improvise a faster turnaround.

STRUCTURE
- Address what the lead just said directly. One short paragraph, ideally
  one or two sentences.
- If a next step is genuinely the right move, it's usually a soft handoff
  ("happy to take care of that today", "send me the address and I'll
  pull a quick mock", "no worries — let me know if anything changes").
  Confident, low-friction, not pushy. Often a simple acknowledgement
  with no ask is correct (e.g. when they say "no thanks" or "all good").
- ONE clean next step OR no next step. Never two.

FORMAT
- Length: target ≤ 160 characters; hard ceiling 320 (two SMS segments).
  Reply length should track the lead's last message — if they sent five
  words, a one-line reply is right; don't bury them.
- Lowercase openers are fine ("yeah, no worries" / "fair enough" /
  "sounds good"). Drop the final full stop if it reads more natural.
- At most ONE exclamation, and only on a friendly opener if it really
  fits. None at all is usually better in a reply.

{_AI_TELLS}

- Output ONLY the message text. No quotes, no labels, no explanation.
"""


def build_user_prompt(
    *,
    campaign_goal: str | None,
    lead_short_name: str | None,
    lead_category: str | None,
    message_history: list[dict[str, str]],
) -> str:
    """User prompt — minimal context, thread is the source of truth."""

    parts: list[str] = ["Conversation so far (oldest first, most recent last):"]
    if not message_history:
        parts.append("(no prior messages)")
    else:
        for m in message_history:
            role = m.get("role", "?")
            label = {
                "ai": "you",
                "human": "you",
                "lead": "lead",
            }.get(role, role)
            content = (m.get("content") or "").strip()
            parts.append(f"[{label}] {content}")

    parts.append("")

    recipient_bits: list[str] = []
    if lead_short_name:
        recipient_bits.append(f"Recipient: {lead_short_name}")
    if lead_category:
        recipient_bits.append(f"Category: {lead_category}")
    if recipient_bits:
        parts.append(" | ".join(recipient_bits))

    if campaign_goal:
        parts.append(f"Eventual goal of the conversation: {campaign_goal}")

    parts.extend(
        [
            "",
            "Write the next reply from 'you'. Address what the lead just said. "
            "Do not re-pitch, do not re-introduce yourself, do not restate the "
            "original observation. ≤160 characters when possible.",
        ]
    )

    return "\n".join(parts)


__all__ = ["PROMPT_VERSION", "build_system_prompt", "build_user_prompt"]
